/**
 * Fixture builders for Phase 2 Increment 19 — real E2E coverage of
 * CSV / XLS / recovery open paths.
 *
 * These builders produce the smallest deterministic fixtures that
 * exercise the coordinator's `prepareWorkbookForOpen` conversion +
 * recovery branches. The Rust sidecar opens the converted XLSX output;
 * the CSV/XLS inputs are NOT opened by the sidecar directly.
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { randomUUID } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import JSZip from 'jszip'

// ── CSV fixture ───────────────────────────────────────────────────────

/**
 * Create a minimal CSV file with deterministic content.
 *
 * The CSV conversion path (`csvToXlsxBuffer` from xlsx-gateway) reads
 * the CSV bytes, decodes them (auto-detecting encoding), and converts
 * to XLSX. The fixture has 3 rows × 2 columns so the converted XLSX
 * can be read back and verified.
 *
 * @param path — absolute path to write the CSV file
 */
export function writeCsvFixture(path: string): void {
  const csv = 'Name,Value\nAlpha,10\nBeta,20\nGamma,30\n'
  writeFileSync(path, csv, 'utf8')
}

// ── XLS fixture ───────────────────────────────────────────────────────

/**
 * Create a minimal XLS (BIFF8) fixture compatible with the Rust sidecar's
 * `convert_workbook` command.
 *
 * The sidecar uses `calamine` (a Rust spreadsheet reader) to parse .xls
 * files. Calamine supports BIFF2/3/4/5/8 formats. The fixture is a real
 * .xls file generated by LibreOffice with:
 *   Sheet1: A1="Hello", B1=42, A2="World", B2=99
 *
 * The fixture is committed to the repository (5.6KB) — it's small and
 * deterministic. A source generator is NOT practical here because the
 * BIFF8 binary format is too complex to hand-craft reliably.
 *
 * @param path — absolute path to copy the XLS fixture to
 */
export function writeXlsFixture(path: string): void {
  const fixturePath = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'minimal.xls')
  const bytes = readFileSync(fixturePath)
  writeFileSync(path, bytes)
}

// ── XLSX fixture (for recovery tests) ─────────────────────────────────

/**
 * Create a minimal XLSX fixture with deterministic cell content.
 * Used as the "original" file for recovery tests.
 */
export async function buildMinimalXlsx(): Promise<Buffer> {
  const zip = new JSZip()
  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>`)

  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`)

  zip.file('xl/workbook.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="Sheet1" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>`)

  zip.file('xl/_rels/workbook.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>`)

  zip.file('xl/worksheets/sheet1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row r="1" spans="1:2">
      <c r="A1" t="inlineStr"><is><t>Original</t></is></c>
      <c r="B1"><v>100</v></c>
    </row>
  </sheetData>
</worksheet>`)

  return zip.generateAsync({ type: 'nodebuffer' })
}

/**
 * Create a minimal XLSX fixture with DIFFERENT content (for recovery).
 * Used as the "recovery copy" — newer than the original.
 */
export async function buildRecoveryXlsx(): Promise<Buffer> {
  const zip = new JSZip()
  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>`)

  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`)

  zip.file('xl/workbook.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="Sheet1" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>`)

  zip.file('xl/_rels/workbook.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>`)

  zip.file('xl/worksheets/sheet1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row r="1" spans="1:2">
      <c r="A1" t="inlineStr"><is><t>Recovered</t></is></c>
      <c r="B1"><v>999</v></c>
    </row>
  </sheetData>
</worksheet>`)

  return zip.generateAsync({ type: 'nodebuffer' })
}

// ── Invalid XLS fixture (for failure path) ─────────────────────────────

/**
 * Create an invalid XLS file — garbage bytes with .xls extension.
 * Used to test that conversion failure produces a typed error + cleans
 * up the conversion temp directory (no leak).
 */
export function writeInvalidXlsFixture(path: string): void {
  // Not a valid OLE2 compound document (wrong magic bytes).
  writeFileSync(path, Buffer.from('This is not a valid XLS file\n'))
}
